# Generated by Django 4.2 on 2023-04-09 15:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Общая информация')),
            ],
        ),
        migrations.AlterField(
            model_name='new',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=100000, verbose_name='Подробное описание статьи'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.jpg', null=True, upload_to='', verbose_name='Загрузите аватар для профиля'),
        ),
    ]
