# Generated by Django 4.2 on 2023-04-15 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_upload',
            field=models.FileField(upload_to='static/midi', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mid', 'mp3'])]),
        ),
    ]
