# Generated by Django 4.2.1 on 2023-05-14 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_task_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subject', verbose_name='Название урока'),
        ),
    ]
