# Generated by Django 4.2 on 2023-04-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_file_file_upload_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='files/images/default.jpg', null=True, upload_to='images', verbose_name='Загрузите аватар для профиля'),
        ),
    ]
