# Generated by Django 4.2.1 on 2023-05-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='groups',
        ),
        migrations.AddField(
            model_name='task',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='base.groupnumber'),
        ),
    ]
