# Generated by Django 4.2.1 on 2023-05-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_task_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='grouped',
            field=models.BooleanField(default=False),
        ),
    ]
