# Generated by Django 4.2 on 2023-04-15 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='default_name', max_length=75),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_upload',
            field=models.FileField(upload_to='midi', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mid', 'midi'])]),
        ),
    ]
