# Generated by Django 4.2 on 2023-05-09 14:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_file_file_name_alter_file_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='rewards',
            field=ckeditor.fields.RichTextField(default='Временно недоступно', verbose_name='Заслуги школы'),
        ),
        migrations.AddField(
            model_name='about',
            name='teachers',
            field=ckeditor.fields.RichTextField(default='Временно недоступно', verbose_name='Информация об учителях'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/profile-pictures/default.jpg', null=True, upload_to='files/images/profile-pictures', verbose_name='Загрузите аватар для профиля'),
        ),
    ]
