# Generated by Django 4.2.1 on 2023-05-15 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_userfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='student_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учащийся'),
        ),
    ]
