# Generated by Django 4.2 on 2023-05-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/profile-pictures/default.jpg', null=True, upload_to='images/', verbose_name='Загрузите аватар для профиля'),
        ),
    ]
