# Generated by Django 4.2.1 on 2023-05-12 15:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='department_name',
            field=models.CharField(default='Департамент', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='f',
            field=models.CharField(default='Фамилия', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='i',
            field=models.CharField(default='Имя', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='instrument_name',
            field=models.CharField(default='Инструмент', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='o',
            field=models.CharField(default='Отчество', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_first_name',
            field=models.CharField(default='Имя представителя 1', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_first_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+375111231212', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_second_name',
            field=models.CharField(default='Имя представителя 2', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_second_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+375111231212', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='rewards',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='start_year',
            field=models.DateField(default='2000-12-12'),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_name',
            field=models.CharField(default='Учитель', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+375001231231', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='user_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+375111231212', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='years',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_upload',
            field=models.FileField(upload_to='library'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('admin', 'Администратор'), ('student', 'Ученик'), ('concertmaster', 'Концертмейстер'), ('editor', 'Редактор'), ('teacher', 'Учитель')], default='student', max_length=20),
        ),
    ]
