# Generated by Django 4.2.1 on 2023-05-12 17:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_event_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parent_first_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+000000000000', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent_second_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+000000000000', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='teacher_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+000000000000', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+000000000000', max_length=128, region=None),
        ),
    ]
