# Generated by Django 4.2.1 on 2023-05-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_user_parent_first_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='Номер группы', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250)),
                ('choices', models.ManyToManyField(blank=True, to='base.groupnumber')),
            ],
        ),
    ]
